### ISSUE TITLE
esprima causing Unexpected Token error

### ISSUE THREAD

**Issue by maximumdata** [sstur/js2php#3]
```
Processing file `index.js` ...
/usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:3872
            throw e;
            ^

Error: Line 5: Unexpected token >
    at throwError (/usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:1213:9)
    at parsePrimaryExpression (/usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:1567:16)
    at /usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38
    at trackLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:3504:61)
    at parsePostfixExpression (/usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:1703:20)
    at /usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38
    at parseUnaryExpression (/usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:1784:16)
    at /usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:3609:38
    at parseMultiplicativeExpression (/usr/local/lib/node_modules/jstophp/node_modules/rocambole/node_modules/esprima/esprima.js:1790:20)
```

Getting this error every time I try to run js2php on a .js file in an express project. 
macOS Sierra 10.12.4
node 7.8.0
npm 4.2.0

**Comment by sstur** [comment]
I expect this is because your js file contains newer syntax than what's supported in js2php.

Can you post the code you're trying to process?

This project is a few years old now and doesn't support any ES6 or newer JavaScript features. You might need to run your code through Babel before using js2php.

**Comment by dagi377** [comment]
simply set your **.babelrc** file to your selected preset
```
{
  "presets": ["es2015"]
  // "plugins": ["istanbul"]
}

```
